Added gametest system

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -33,6 +33,49 @@ jobs:
       # Run eslint
       - name: Test eslint
         run: npm run lint
+  
+  gametest:
+    runs-on: ubuntu-latest
+
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v3
+
+      # Install npm
+      - uses: bahmutov/npm-install@v1
+        with:
+          node-version: 16
+
+      - name: Download bedrock dedicated server
+        run: |
+          wget https://www.minecraft.net/bedrockdedicatedserver/bin-linux-preview/bedrock-server-1.21.110.24.zip -O bedrock-server.zip
+          unzip bedrock-server.zip -d bedrock-server
+          chmod +x bedrock-server/bedrock_server
+
+      - name: Run build script (server + gametest)
+        run: |
+          node build.mjs --target=server --gametest
+          echo "import { world } from '@minecraft/server'; world.afterEvents.worldLoad.subscribe(() => world.getDimension('overworld').runCommand('gametest runset worldedit'));" >> builds/WorldEditBP/scripts/gametest/index.js
+      
+      - name: Set up Bedrock server
+        run: |
+          mkdir -p "bedrock-server/worlds/Bedrock level"
+          cp -r test/world/*  "bedrock-server/worlds/Bedrock level/"
+          node tools/add_to_world.mjs --world-path="bedrock-server/worlds/Bedrock level"
+
+      - name: Run Server
+        run: |
+            cd bedrock-server
+            echo "Running Bedrock server..."
+            ./bedrock_server >../server_output.log 2>&1 &
+            SERVER_PID=$!
+            sleep 10  # Let the server run for a bit
+            kill $SERVER_PID
+            if grep -q "onTestFailed" ../server_output.log; then
+              echo "Error during gametest execution:"
+              cat ../server_output.log
+              exit 1
+            fi
 
   # This workflow contains a single job called "build"
   build:
